language: java

before_install:
  - sudo apt-get update -qq > /dev/null

install:
  - sudo apt-get install apache2 php5 libapache2-mod-php5 -qq > /dev/null

script:
  - cd src/test/resources
  - sudo ./installTestEnvironment.sh
  - cd ../../..
  - ls -lR /var/www/dokuwikiITestsForXmlRpcClient_dokuwiki-2014-09-29a/data
  - mvn -q test
